#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Wi-Fi support
SB_CONFIG_WIFI_NRF70=y
# Partition manage deprecated after NCS v3.3.0
SB_CONFIG_PARTITION_MANAGER=n